set_property PACKAGE_PIN U21 [get_ports {servo_control_output[3]}]
set_property PACKAGE_PIN U22 [get_ports {servo_control_output[2]}]
set_property PACKAGE_PIN T21 [get_ports {servo_control_output[1]}]
set_property PACKAGE_PIN T22 [get_ports {servo_control_output[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {servo_control_output[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {servo_control_output[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {servo_control_output[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {servo_control_output[0]}]
