@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Nov 05 08:55:21 -0500 2020
REM SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 61cce61000874ef685e865093eb9cacc --incr --debug typical --relax --mt 2 -L xil_defaultlib -L axi_rc_servo_controller -L secureip --snapshot axi_rc_servo_controller_testbench_behav xil_defaultlib.axi_rc_servo_controller_testbench -log elaborate.log"
call xelab  -wto 61cce61000874ef685e865093eb9cacc --incr --debug typical --relax --mt 2 -L xil_defaultlib -L axi_rc_servo_controller -L secureip --snapshot axi_rc_servo_controller_testbench_behav xil_defaultlib.axi_rc_servo_controller_testbench -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
